$script = <<-SCRIPT
echo execute script
echo 3 |  sudo update-alternatives --config editor
# sudo useradd -G sudo -m -s /bin/bash ansible 
# mkdir /home/ansible/.ssh || true
cat > /etc/motd << EO\F
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░▄███████▄░░░░░░░░░░
░░░░░░░░░▐██▀░░░▀██▌░░░░░░░░░
░░░░░░░░░▐██░░░░░██▌░░░░░░░░░
░░░░░░░░░▐██▄░░░▄██▌░░░░░░░░░
░░░░░░░░░░▀███████▀░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░▐███▄███▌░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░░░░░░░░░░░▐█▄█▌░░░░░░░░░░░░
░░▄█▄░░░░░░░▐█▄█▌░░░░░░░▄█▄░░
▄█████▄░░░░░▐█▄█▌░░░░░▄█████▄
░░███░░░░░░░▐█▄█▌░░░░░░░███░░
░░███▄░░░░░▄██▄██▄░░░░░▄███░░
░░▀████▄▄▄████▄████▄▄▄████▀░░
░░░░▀█████████▄█████████▀░░░░
░░░░░░▀███████▄███████▀░░░░░░
░░░░░░░░░▀████▄████▀░░░░░░░░░
░░░░░░░░░░░░▀█▄█▀░░░░░░░░░░░░
░░░░░░░░░░░░░░▀░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
EOF
# chown  ansible:ansible /home/ansible/.ssh
# chown  ansible:ansible /home/ansible/.ssh/authorized_keys
# chmod 644 /home/ansible/.ssh/authorized_keys
# chmod 700 /home/ansible/.ssh 
# echo "ansible:ansible" | sudo chpasswd
# chmod 770 /etc/sudoers
# #sed -i 's/ansible.*/ansible ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers || echo "ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# sed -i '/ansible/d' /etc/sudoers
# echo "ansible ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# chmod 440 /etc/sudoers
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox"
  (1..1).each do |i|
    config.vm.define "master-#{i}" do |master|
      master.vm.network "public_network", bridge: "enp24s0", ip: "192.168.88.#{10 + i}"
      master.vm.network "private_network", ip: "192.168.11.#{10 + i}"
      master.vm.hostname = "master-#{i}"
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/useradd_ansible.yml"
        ansible.extra_vars = {
          hosts: "all",
        }
      master.vm.provision "shell", inline: $script
      end
      master.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
  end
  (1..4).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "public_network", bridge: "enp24s0", ip: "192.168.88.#{13 + i}"
      node.vm.network "private_network", ip: "192.168.11.#{13 + i}"
      node.vm.hostname = "node-#{i}"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/useradd_ansible.yml"
        ansible.extra_vars = {
          hosts: "all",
        }
      node.vm.provision "shell", inline: $script
      end
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
    end
  end
end
