---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx-test-zone
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
      
      types {}
      default_type text/html;

      location / {
        return 200 '$hostname\n$time_local\n80\n';
      }
    }
    server {
      listen 81 default_server;
      server_name _;
      
      types {}
      default_type text/html;

      location / {
        return 200 '$hostname\n$time_local\n81\n';
      }
    }
