apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: nginx
spec:
  domain: nginx-test-zone
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
