---
- name:  Nodes preparation
  hosts: rancher-k8s
  serial: 6
  become: true
  vars:
    docker_install_hold: false
  roles:
    - linux_os_update
    # - hosts
    - docker_install
  tags:
    - docker