---
galaxy_info:
  role_name: k8s_install
  author: VikSh404
  description: Install packages for k8s.
  license: "MIT"
  min_ansible_version: 2.11
  platforms:
    - name: ubuntu
      versions:
        - 18
  galaxy_tags:
    - k8s
