---
- name: Restart etcd
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    enabled: yes
    daemon_reload: yes
    
- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes 

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes 

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes 

- name: Restart kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    enabled: yes
    daemon_reload: yes 

    