---
- name: Restart etcd
  throttle: 1
  systemd:
    name: etcd
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: "'patroni-etcd' in group_names"

- name: Restart patroni
  throttle: 1
  systemd:
    name: patroni
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: "'patroni-database' in group_names"

- name: Restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
  when: "'keepalived' in group_names"
