---
- name:  Install prometheus node exporter
  hosts: mv
  serial: 2
  roles:
    # - hostname_from_inventory
    - docker_install
    - linux_os_update
    - prometheus_node_exporter_install
  # tags:
  #   - prometheus


