---
- name:  Nodes preparation
  hosts: vm
  serial: 5
  become: true
  vars:
    docker_install_hold: true
    k8s_install_hold: true
  roles:
    - linux_os_update
    - prometheus_node_exporter_install
    - docker_install
    - k8s_install
    - k8s_preconfigure_network
  tags:
    - k8s_prepare

- name: Kube init cluster
  hosts: controllers
  serial: 5
  become: true
  roles:
    - k8s_init
  tags:
    - control_plane_init

- name: Kube init cluster
  hosts: workers
  serial: 5
  become: true
  roles:
    - k8s_join_node
  tags:
    - join_nodes
