---
- name: Configure servers
  hosts: k8sthw-controllers
  become: true

  tasks:
  - name: Debug
    debug:
      msg:
        - "NAME-from-host:       {{ ansible_host }}"
        - "HOSTNAME-from-facts:  {{ ansible_hostname }}"
        - "IP-from-facts:        {{ ansible_all_ipv4_addresses[0] }}"
        - "Subnet:    {{ subnet }}"
        - "Gateway:   {{ subnet | ipaddr('next_usable')  }}"
        - "DNS:       {{ subnet | ipaddr('last_usable')  }}"
        - "ID:                    {{ ID }}"
        - "HOSTNAME:              {{ HOSTNAME }}"
        - "IP:                    {{ IP }}"
        - "ETCD_INITIAL_CLUSTER:  {{ ETCD_INITIAL_CLUSTER }}"
        - "{{ groups['k8sthw'] }} "
