---
- name: Configure servers
  hosts: all
  become: true

  tasks:
  - name: Debug
    debug:
       msg:
         - "{{ ansible_hostname }}"
         - "{{ ansible_all_ipv4_addresses }}"
         - "{{ subnet }}"
         - "{{ subnet | ipaddr('next_usable')  }}"
         - "{{ subnet | ipaddr('last_usable')  }}"

